apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdev-demo-aggregator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      containers:
      - env:
        - name: GROUP_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: BOOTSTRAP_SERVER
          valueFrom:
            configMapKeyRef:
              key: appdevdemo.property.BOOTSTRAP_SERVER
              name: appdev-demo-cm
        - name: CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: appdevdemo.property.CLIENT_ID
              name: appdev-demo-cm
        - name: CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              key: appdevdemo.property.CLIENT_SECRET
              name: appdev-demo-cm
        - name: OAUTH_TOKEN_ENDPOINT_URI
          valueFrom:
            configMapKeyRef:
              key: appdevdemo.property.OAUTH_TOKEN_ENDPOINT_URI
              name: appdev-demo-cm
        - name: APP_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        image: quay.io/jmaira/appdev_aggregator:7338231
        name: aggregator
        ports:
        - containerPort: 8080
          protocol: TCP
