kind: Deployment
apiVersion: apps/v1
metadata:
  name: appdev-demo-aggregator-deployment
  # namespace: appdevdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator
  template:
    metadata:
      
      labels:
        app: aggregator
    spec:
      containers:
        - name: aggregator
          image: 'quay.io/jmaira/appdev_aggregator:0.0.5'
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: GROUP_ID
              value: appdev-demo-group-quarkus-weathrs-e7dd6ed342f5
            - name: BOOTSTRAP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: appdev-demo-cm
                  key: appdevdemo.property.BOOTSTRAP_SERVER
            - name: CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: appdev-demo-cm
                  key: appdevdemo.property.CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: appdev-demo-cm
                  key: appdevdemo.property.CLIENT_SECRET
            - name: OAUTH_TOKEN_ENDPOINT_URI
              valueFrom:
                configMapKeyRef:
                  name: appdev-demo-cm
                  key: appdevdemo.property.OAUTH_TOKEN_ENDPOINT_URI
            - name: APP_ID
              valueFrom:
                configMapKeyRef:
                  name: appdev-demo-cm
                  key: appdevdemo.property.APP_ID
            - name: GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: appdev-demo-cm
                  key: appdevdemo.property.GROUP_ID
          
