kind: Deployment
apiVersion: apps/v1
metadata:
  name: appdev-demo-producer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
     
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: 'quay.io/jmaira/appdev_producer:48fba73'
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: appdev-demo-cm
                  key: appdevdemo.property.GROUP_ID
            - name: BOOTSTRAP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: appdev-demo-cm
                  key: appdevdemo.property.BOOTSTRAP_SERVER
            - name: CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: appdev-demo-cm
                  key: appdevdemo.property.CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: appdev-demo-cm
                  key: appdevdemo.property.CLIENT_SECRET
            - name: OAUTH_TOKEN_ENDPOINT_URI
              valueFrom:
                configMapKeyRef:
                  name: appdev-demo-cm
                  key: appdevdemo.property.OAUTH_TOKEN_ENDPOINT_URI
            - name: APP_ID
              valueFrom:
                configMapKeyRef:
                  name: appdev-demo-cm
                  key: appdevdemo.property.APP_ID
          
