apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdev-demo-producer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - env:
        - name: GROUP_ID
          valueFrom:
            configMapKeyRef:
              key: appdevdemo.property.GROUP_ID
              name: appdev-demo-cm
        - name: BOOTSTRAP_SERVER
          valueFrom:
            configMapKeyRef:
              key: appdevdemo.property.BOOTSTRAP_SERVER
              name: appdev-demo-cm
        - name: CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: appdevdemo.property.CLIENT_ID
              name: appdev-demo-cm
        - name: CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              key: appdevdemo.property.CLIENT_SECRET
              name: appdev-demo-cm
        - name: OAUTH_TOKEN_ENDPOINT_URI
          valueFrom:
            configMapKeyRef:
              key: appdevdemo.property.OAUTH_TOKEN_ENDPOINT_URI
              name: appdev-demo-cm
        - name: APP_ID
          valueFrom:
            configMapKeyRef:
              key: appdevdemo.property.APP_ID
              name: appdev-demo-cm
        image: quay.io/jmaira/appdev_producer:db0d1f0
        name: producer
        ports:
        - containerPort: 8080
          protocol: TCP
